export { TemplateAbout } from './AboutTemplate/aboutTemplate'
export { TemplateArticleList } from './ArticleListTemplate/articleListTemplate'
export { TemplateArticleReader } from './ArticleReaderTemplate/articleReaderTemplate'
export { TemplateGrammar } from './GrammarTemplate/grammarTemplate'
export { TemplateHome } from './HomeTemplate/homeTemplate'
export { TemplateLanding } from './LandingTemplate/landingTemplate'
export { TemplatePrivacy } from './PrivacyTemplate'
export { TemplateQuizResult } from './QuizResultTemplate/quizResultTemplate'
export { isAnswerCorrect, TemplateQuiz } from './QuizTemplate/quizTemplate'
export { TemplateTerms } from './TermsTemplate'
